---
 queries:
  - "\"হয়েছে\""
 papers:
  - "prothom_alo"
  - "kaler_kantho"
  - "samakal"
  - "bd_news"
 date_ranges: 
  - ["1/1/1996", "12/31/2012", 1825]
  - ["1/1/2013", "12/31/2021", 15]

 output_dir: "data/CommonKeyword"
 output_file: "{paper}_serp_{query}.json"
 quote_sub: "[RVDQUOTE]"
 overwrite: False
 skip_existing: True

 searchnws: False
 gl: "bd"
 hl: "bn"
 filter: '0'
 num: 100
 SERPAPI_KEY: [KEY]
