---
 searches:
  popular:
    queries:
      - "\"হয়েছে\""
    papers:
      - "the_daily_janakantha"
      - "the_daily_jugantor"
      - "the_daily_ittefaq"
      - "amader_shomoy"
      - "bhorer_kagoj"
      - "daily_manab_zamin"
      - "alokito_bangladesh"
      - "the_sangbad"
      - "the_daily_inqilab"
      - "jaijaidin"
      - "daily_naya_diganta"
      - "the_azadi"
      - "daily_sangram"
      - "sangbad_pratidin"
      - "the_daily_star"
    date_ranges: 
      - ["1/1/1996", "12/31/2015", 1825]
      - ["1/1/2016", "12/31/2021", 50]
  prothom_alo:
    queries:
      - "\"হয়েছে\""
    papers:
      - "prothom_alo"
    date_ranges: 
      - ["1/1/1996", "12/31/2015", 1825]

 output_dir: "testing"
 output_file: "dense_serp.csv"
 completed_searches_file: "testing/completed"
 overwrite: False
 skip_existing: True

 searchnws: False
 gl: "bd"
 hl: "bn"
 filter: '0'
 num: 100
 SERPAPI_KEY: [KEY]
